#pragma once

typedef enum {
  MCI_CAN_EVENT_RX = 0,
  MCI_CAN_EVENT_TX,
  MCI_CAN_EVENT_FAULT,
  NUM_MCI_CAN_EVENTS
} MciCanEvent;

typedef enum {
  MCI_DRIVE_FSM_EVENT_OFF_STATE = NUM_MCI_CAN_EVENTS + 1,
  MCI_DRIVE_FSM_EVENT_DRIVE_STATE,
  MCI_DRIVE_FSM_EVENT_REVERSE_STATE,
  NUM_MCI_DRIVE_FSM_EVENTS
} MciDriveFsmEvent;
