/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: adc.proto */

#ifndef PROTOBUF_C_adc_2eproto__INCLUDED
#define PROTOBUF_C_adc_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MuAdcStore MuAdcStore;


/* --- enums --- */


/* --- messages --- */

struct  _MuAdcStore
{
  ProtobufCMessage base;
  size_t n_reading;
  uint32_t *reading;
};
#define MU_ADC_STORE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mu_adc_store__descriptor) \
    , 0,NULL }


/* MuAdcStore methods */
void   mu_adc_store__init
                     (MuAdcStore         *message);
size_t mu_adc_store__get_packed_size
                     (const MuAdcStore   *message);
size_t mu_adc_store__pack
                     (const MuAdcStore   *message,
                      uint8_t             *out);
size_t mu_adc_store__pack_to_buffer
                     (const MuAdcStore   *message,
                      ProtobufCBuffer     *buffer);
MuAdcStore *
       mu_adc_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mu_adc_store__free_unpacked
                     (MuAdcStore *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MuAdcStore_Closure)
                 (const MuAdcStore *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mu_adc_store__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_adc_2eproto__INCLUDED */
