/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ads1259.proto */

#ifndef PROTOBUF_C_ads1259_2eproto__INCLUDED
#define PROTOBUF_C_ads1259_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MuAds1259Store MuAds1259Store;


/* --- enums --- */


/* --- messages --- */

struct  _MuAds1259Store
{
  ProtobufCMessage base;
  uint32_t reading;
};
#define MU_ADS1259_STORE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mu_ads1259_store__descriptor) \
    , 0 }


/* MuAds1259Store methods */
void   mu_ads1259_store__init
                     (MuAds1259Store         *message);
size_t mu_ads1259_store__get_packed_size
                     (const MuAds1259Store   *message);
size_t mu_ads1259_store__pack
                     (const MuAds1259Store   *message,
                      uint8_t             *out);
size_t mu_ads1259_store__pack_to_buffer
                     (const MuAds1259Store   *message,
                      ProtobufCBuffer     *buffer);
MuAds1259Store *
       mu_ads1259_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mu_ads1259_store__free_unpacked
                     (MuAds1259Store *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MuAds1259Store_Closure)
                 (const MuAds1259Store *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mu_ads1259_store__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_ads1259_2eproto__INCLUDED */
