/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gpio.proto */

#ifndef PROTOBUF_C_gpio_2eproto__INCLUDED
#define PROTOBUF_C_gpio_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MuGpioStore MuGpioStore;


/* --- enums --- */


/* --- messages --- */

struct  _MuGpioStore
{
  ProtobufCMessage base;
  size_t n_state;
  protobuf_c_boolean *state;
};
#define MU_GPIO_STORE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mu_gpio_store__descriptor) \
    , 0,NULL }


/* MuGpioStore methods */
void   mu_gpio_store__init
                     (MuGpioStore         *message);
size_t mu_gpio_store__get_packed_size
                     (const MuGpioStore   *message);
size_t mu_gpio_store__pack
                     (const MuGpioStore   *message,
                      uint8_t             *out);
size_t mu_gpio_store__pack_to_buffer
                     (const MuGpioStore   *message,
                      ProtobufCBuffer     *buffer);
MuGpioStore *
       mu_gpio_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mu_gpio_store__free_unpacked
                     (MuGpioStore *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MuGpioStore_Closure)
                 (const MuGpioStore *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mu_gpio_store__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_gpio_2eproto__INCLUDED */
