/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mcp23008.proto */

#ifndef PROTOBUF_C_mcp23008_2eproto__INCLUDED
#define PROTOBUF_C_mcp23008_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MuMcp23008Store MuMcp23008Store;


/* --- enums --- */


/* --- messages --- */

struct  _MuMcp23008Store
{
  ProtobufCMessage base;
  size_t n_state;
  protobuf_c_boolean *state;
};
#define MU_MCP23008_STORE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mu_mcp23008_store__descriptor) \
    , 0,NULL }


/* MuMcp23008Store methods */
void   mu_mcp23008_store__init
                     (MuMcp23008Store         *message);
size_t mu_mcp23008_store__get_packed_size
                     (const MuMcp23008Store   *message);
size_t mu_mcp23008_store__pack
                     (const MuMcp23008Store   *message,
                      uint8_t             *out);
size_t mu_mcp23008_store__pack_to_buffer
                     (const MuMcp23008Store   *message,
                      ProtobufCBuffer     *buffer);
MuMcp23008Store *
       mu_mcp23008_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mu_mcp23008_store__free_unpacked
                     (MuMcp23008Store *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MuMcp23008Store_Closure)
                 (const MuMcp23008Store *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mu_mcp23008_store__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_mcp23008_2eproto__INCLUDED */
