/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pca9539r.proto */

#ifndef PROTOBUF_C_pca9539r_2eproto__INCLUDED
#define PROTOBUF_C_pca9539r_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _MuPca9539rStore MuPca9539rStore;


/* --- enums --- */


/* --- messages --- */

struct  _MuPca9539rStore
{
  ProtobufCMessage base;
  size_t n_state;
  protobuf_c_boolean *state;
};
#define MU_PCA9539R_STORE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&mu_pca9539r_store__descriptor) \
    , 0,NULL }


/* MuPca9539rStore methods */
void   mu_pca9539r_store__init
                     (MuPca9539rStore         *message);
size_t mu_pca9539r_store__get_packed_size
                     (const MuPca9539rStore   *message);
size_t mu_pca9539r_store__pack
                     (const MuPca9539rStore   *message,
                      uint8_t             *out);
size_t mu_pca9539r_store__pack_to_buffer
                     (const MuPca9539rStore   *message,
                      ProtobufCBuffer     *buffer);
MuPca9539rStore *
       mu_pca9539r_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   mu_pca9539r_store__free_unpacked
                     (MuPca9539rStore *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MuPca9539rStore_Closure)
                 (const MuPca9539rStore *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mu_pca9539r_store__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_pca9539r_2eproto__INCLUDED */
