#pragma once

#include "flash.h"
#include "flash_mcu.h"

#define BOOTLOADER_CONFIG_PAGE_1_START ((void *)(FLASH_BASE_ADDR + 8 * FLASH_PAGE_BYTES))
#define BOOTLOADER_CONFIG_PAGE_2_START ((void *)(FLASH_BASE_ADDR + 9 * FLASH_PAGE_BYTES))
#define BOOTLOADER_APPLICATION_START ((void *)(FLASH_BASE_ADDR + 10 * FLASH_PAGE_BYTES))
#define BOOTLOADER_APPLICATION_SIZE ((size_t)(FLASH_BASE_ADDR + 11 * FLASH_PAGE_BYTES))
#define BOOTLOADER_RAM_START ((void *)(FLASH_BASE_ADDR + 12 * FLASH_PAGE_BYTES))
#define BOOTLOADER_RAM_SIZE ((size_t)(FLASH_BASE_ADDR + 13 * FLASH_PAGE_BYTES))
#define BOOTLOADER_VECTOR_TABLE_SIZE ((size_t)(FLASH_BASE_ADDR + 14 * FLASH_PAGE_BYTES))
