/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: adc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "adc.pb-c.h"
void mx_adc_store__init(MxAdcStore *message) {
  static const MxAdcStore init_value = MX_ADC_STORE__INIT;
  *message = init_value;
}
size_t mx_adc_store__get_packed_size(const MxAdcStore *message) {
  assert(message->base.descriptor == &mx_adc_store__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_adc_store__pack(const MxAdcStore *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_adc_store__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_adc_store__pack_to_buffer(const MxAdcStore *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_adc_store__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxAdcStore *mx_adc_store__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (MxAdcStore *)protobuf_c_message_unpack(&mx_adc_store__descriptor, allocator, len, data);
}
void mx_adc_store__free_unpacked(MxAdcStore *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_adc_store__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_adc_store__field_descriptors[1] = {
  {
      "reading", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_UINT32,
      offsetof(MxAdcStore, n_reading), offsetof(MxAdcStore, reading), NULL, NULL,
      0 | PROTOBUF_C_FIELD_FLAG_PACKED, /* flags */
      0, NULL, NULL                     /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_adc_store__field_indices_by_name[] = {
  0, /* field[0] = reading */
};
static const ProtobufCIntRange mx_adc_store__number_ranges[1 + 1] = { { 1, 0 }, { 0, 1 } };
const ProtobufCMessageDescriptor mx_adc_store__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxAdcStore",
  "MxAdcStore",
  "MxAdcStore",
  "",
  sizeof(MxAdcStore),
  1,
  mx_adc_store__field_descriptors,
  mx_adc_store__field_indices_by_name,
  1,
  mx_adc_store__number_ranges,
  (ProtobufCMessageInit)mx_adc_store__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
