/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ads1259.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ads1259.pb-c.h"
void mx_ads1259_store__init(MxAds1259Store *message) {
  static const MxAds1259Store init_value = MX_ADS1259_STORE__INIT;
  *message = init_value;
}
size_t mx_ads1259_store__get_packed_size(const MxAds1259Store *message) {
  assert(message->base.descriptor == &mx_ads1259_store__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_ads1259_store__pack(const MxAds1259Store *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_ads1259_store__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_ads1259_store__pack_to_buffer(const MxAds1259Store *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_ads1259_store__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxAds1259Store *mx_ads1259_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                         const uint8_t *data) {
  return (MxAds1259Store *)protobuf_c_message_unpack(&mx_ads1259_store__descriptor, allocator, len,
                                                     data);
}
void mx_ads1259_store__free_unpacked(MxAds1259Store *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_ads1259_store__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_ads1259_store__field_descriptors[1] = {
  {
      "reading", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
      offsetof(MxAds1259Store, reading), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                                   /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_ads1259_store__field_indices_by_name[] = {
  0, /* field[0] = reading */
};
static const ProtobufCIntRange mx_ads1259_store__number_ranges[1 + 1] = { { 1, 0 }, { 0, 1 } };
const ProtobufCMessageDescriptor mx_ads1259_store__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxAds1259Store",
  "MxAds1259Store",
  "MxAds1259Store",
  "",
  sizeof(MxAds1259Store),
  1,
  mx_ads1259_store__field_descriptors,
  mx_ads1259_store__field_indices_by_name,
  1,
  mx_ads1259_store__number_ranges,
  (ProtobufCMessageInit)mx_ads1259_store__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
