/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ads1015.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ads1015.pb-c.h"
void mx_ads1015_store__init(MxAds1015Store *message) {
  static const MxAds1015Store init_value = MX_ADS1015_STORE__INIT;
  *message = init_value;
}
size_t mx_ads1015_store__get_packed_size(const MxAds1015Store *message) {
  assert(message->base.descriptor == &mx_ads1015_store__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_ads1015_store__pack(const MxAds1015Store *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_ads1015_store__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_ads1015_store__pack_to_buffer(const MxAds1015Store *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_ads1015_store__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxAds1015Store *mx_ads1015_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                         const uint8_t *data) {
  return (MxAds1015Store *)protobuf_c_message_unpack(&mx_ads1015_store__descriptor, allocator, len,
                                                     data);
}
void mx_ads1015_store__free_unpacked(MxAds1015Store *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_ads1015_store__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_ads1015_store__field_descriptors[1] = {
  {
      "readings", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_INT32,
      offsetof(MxAds1015Store, n_readings), offsetof(MxAds1015Store, readings), NULL, NULL,
      0 | PROTOBUF_C_FIELD_FLAG_PACKED, /* flags */
      0, NULL, NULL                     /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_ads1015_store__field_indices_by_name[] = {
  0, /* field[0] = readings */
};
static const ProtobufCIntRange mx_ads1015_store__number_ranges[1 + 1] = { { 1, 0 }, { 0, 1 } };
const ProtobufCMessageDescriptor mx_ads1015_store__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxAds1015Store",
  "MxAds1015Store",
  "MxAds1015Store",
  "",
  sizeof(MxAds1015Store),
  1,
  mx_ads1015_store__field_descriptors,
  mx_ads1015_store__field_indices_by_name,
  1,
  mx_ads1015_store__number_ranges,
  (ProtobufCMessageInit)mx_ads1015_store__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
