/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: adt7476a.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "adt7476a.pb-c.h"
void mx_adt7476a_store__init(MxAdt7476aStore *message) {
  static const MxAdt7476aStore init_value = MX_ADT7476A_STORE__INIT;
  *message = init_value;
}
size_t mx_adt7476a_store__get_packed_size(const MxAdt7476aStore *message) {
  assert(message->base.descriptor == &mx_adt7476a_store__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_adt7476a_store__pack(const MxAdt7476aStore *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_adt7476a_store__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_adt7476a_store__pack_to_buffer(const MxAdt7476aStore *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_adt7476a_store__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxAdt7476aStore *mx_adt7476a_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                           const uint8_t *data) {
  return (MxAdt7476aStore *)protobuf_c_message_unpack(&mx_adt7476a_store__descriptor, allocator,
                                                      len, data);
}
void mx_adt7476a_store__free_unpacked(MxAdt7476aStore *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_adt7476a_store__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_adt7476a_store__field_descriptors[2] = {
  {
      "speed", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_UINT32,
      offsetof(MxAdt7476aStore, n_speed), offsetof(MxAdt7476aStore, speed), NULL, NULL,
      0 | PROTOBUF_C_FIELD_FLAG_PACKED, /* flags */
      0, NULL, NULL                     /* reserved1,reserved2, etc */
  },
  {
      "status", 2, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_BOOL,
      offsetof(MxAdt7476aStore, n_status), offsetof(MxAdt7476aStore, status), NULL, NULL,
      0 | PROTOBUF_C_FIELD_FLAG_PACKED, /* flags */
      0, NULL, NULL                     /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_adt7476a_store__field_indices_by_name[] = {
  0, /* field[0] = speed */
  1, /* field[1] = status */
};
static const ProtobufCIntRange mx_adt7476a_store__number_ranges[1 + 1] = { { 1, 0 }, { 0, 2 } };
const ProtobufCMessageDescriptor mx_adt7476a_store__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxAdt7476aStore",
  "MxAdt7476aStore",
  "MxAdt7476aStore",
  "",
  sizeof(MxAdt7476aStore),
  2,
  mx_adt7476a_store__field_descriptors,
  mx_adt7476a_store__field_indices_by_name,
  1,
  mx_adt7476a_store__number_ranges,
  (ProtobufCMessageInit)mx_adt7476a_store__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
