/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gpio.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gpio.pb-c.h"
void mx_gpio_store__init(MxGpioStore *message) {
  static const MxGpioStore init_value = MX_GPIO_STORE__INIT;
  *message = init_value;
}
size_t mx_gpio_store__get_packed_size(const MxGpioStore *message) {
  assert(message->base.descriptor == &mx_gpio_store__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_gpio_store__pack(const MxGpioStore *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_gpio_store__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_gpio_store__pack_to_buffer(const MxGpioStore *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_gpio_store__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxGpioStore *mx_gpio_store__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (MxGpioStore *)protobuf_c_message_unpack(&mx_gpio_store__descriptor, allocator, len, data);
}
void mx_gpio_store__free_unpacked(MxGpioStore *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_gpio_store__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_gpio_store__field_descriptors[1] = {
  {
      "state", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_BOOL, offsetof(MxGpioStore, n_state),
      offsetof(MxGpioStore, state), NULL, NULL, 0 | PROTOBUF_C_FIELD_FLAG_PACKED, /* flags */
      0, NULL, NULL /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_gpio_store__field_indices_by_name[] = {
  0, /* field[0] = state */
};
static const ProtobufCIntRange mx_gpio_store__number_ranges[1 + 1] = { { 1, 0 }, { 0, 1 } };
const ProtobufCMessageDescriptor mx_gpio_store__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxGpioStore",
  "MxGpioStore",
  "MxGpioStore",
  "",
  sizeof(MxGpioStore),
  1,
  mx_gpio_store__field_descriptors,
  mx_gpio_store__field_indices_by_name,
  1,
  mx_gpio_store__number_ranges,
  (ProtobufCMessageInit)mx_gpio_store__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
