/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mcp2515.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mcp2515.pb-c.h"
void mx_mcp2515_store__init(MxMcp2515Store *message) {
  static const MxMcp2515Store init_value = MX_MCP2515_STORE__INIT;
  *message = init_value;
}
size_t mx_mcp2515_store__get_packed_size(const MxMcp2515Store *message) {
  assert(message->base.descriptor == &mx_mcp2515_store__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_mcp2515_store__pack(const MxMcp2515Store *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_mcp2515_store__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_mcp2515_store__pack_to_buffer(const MxMcp2515Store *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_mcp2515_store__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxMcp2515Store *mx_mcp2515_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                         const uint8_t *data) {
  return (MxMcp2515Store *)protobuf_c_message_unpack(&mx_mcp2515_store__descriptor, allocator, len,
                                                     data);
}
void mx_mcp2515_store__free_unpacked(MxMcp2515Store *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_mcp2515_store__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_mcp2515_store__field_descriptors[8] = {
  {
      "tx_id", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, tx_id), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                                 /* reserved1,reserved2, etc */
  },
  {
      "tx_extended", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BOOL, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, tx_extended), NULL, NULL, 0,             /* flags */
      0, NULL, NULL /* reserved1,reserved2, etc */
  },
  {
      "tx_dlc", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, tx_dlc), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                                  /* reserved1,reserved2, etc */
  },
  {
      "tx_data", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, tx_data), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                                   /* reserved1,reserved2, etc */
  },
  {
      "rx_id", 5, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, rx_id), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                                 /* reserved1,reserved2, etc */
  },
  {
      "rx_extended", 6, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BOOL, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, rx_extended), NULL, NULL, 0,             /* flags */
      0, NULL, NULL /* reserved1,reserved2, etc */
  },
  {
      "rx_dlc", 7, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT32, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, rx_dlc), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                                  /* reserved1,reserved2, etc */
  },
  {
      "rx_data", 8, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64, 0, /* quantifier_offset */
      offsetof(MxMcp2515Store, rx_data), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                                   /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_mcp2515_store__field_indices_by_name[] = {
  7, /* field[7] = rx_data */
  6, /* field[6] = rx_dlc */
  5, /* field[5] = rx_extended */
  4, /* field[4] = rx_id */
  3, /* field[3] = tx_data */
  2, /* field[2] = tx_dlc */
  1, /* field[1] = tx_extended */
  0, /* field[0] = tx_id */
};
static const ProtobufCIntRange mx_mcp2515_store__number_ranges[1 + 1] = { { 1, 0 }, { 0, 8 } };
const ProtobufCMessageDescriptor mx_mcp2515_store__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxMcp2515Store",
  "MxMcp2515Store",
  "MxMcp2515Store",
  "",
  sizeof(MxMcp2515Store),
  8,
  mx_mcp2515_store__field_descriptors,
  mx_mcp2515_store__field_indices_by_name,
  1,
  mx_mcp2515_store__number_ranges,
  (ProtobufCMessageInit)mx_mcp2515_store__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
