/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mcp23008.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "mcp23008.pb-c.h"
void mx_mcp23008_store__init(MxMcp23008Store *message) {
  static const MxMcp23008Store init_value = MX_MCP23008_STORE__INIT;
  *message = init_value;
}
size_t mx_mcp23008_store__get_packed_size(const MxMcp23008Store *message) {
  assert(message->base.descriptor == &mx_mcp23008_store__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_mcp23008_store__pack(const MxMcp23008Store *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_mcp23008_store__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_mcp23008_store__pack_to_buffer(const MxMcp23008Store *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_mcp23008_store__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxMcp23008Store *mx_mcp23008_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                           const uint8_t *data) {
  return (MxMcp23008Store *)protobuf_c_message_unpack(&mx_mcp23008_store__descriptor, allocator,
                                                      len, data);
}
void mx_mcp23008_store__free_unpacked(MxMcp23008Store *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_mcp23008_store__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_mcp23008_store__field_descriptors[1] = {
  {
      "state", 1, PROTOBUF_C_LABEL_REPEATED, PROTOBUF_C_TYPE_BOOL,
      offsetof(MxMcp23008Store, n_state), offsetof(MxMcp23008Store, state), NULL, NULL,
      0 | PROTOBUF_C_FIELD_FLAG_PACKED, /* flags */
      0, NULL, NULL                     /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_mcp23008_store__field_indices_by_name[] = {
  0, /* field[0] = state */
};
static const ProtobufCIntRange mx_mcp23008_store__number_ranges[1 + 1] = { { 1, 0 }, { 0, 1 } };
const ProtobufCMessageDescriptor mx_mcp23008_store__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxMcp23008Store",
  "MxMcp23008Store",
  "MxMcp23008Store",
  "",
  sizeof(MxMcp23008Store),
  1,
  mx_mcp23008_store__field_descriptors,
  mx_mcp23008_store__field_indices_by_name,
  1,
  mx_mcp23008_store__number_ranges,
  (ProtobufCMessageInit)mx_mcp23008_store__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
