/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stores.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "stores.pb-c.h"
void mx_log__init(MxLog *message) {
  static const MxLog init_value = MX_LOG__INIT;
  *message = init_value;
}
size_t mx_log__get_packed_size(const MxLog *message) {
  assert(message->base.descriptor == &mx_log__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_log__pack(const MxLog *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_log__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_log__pack_to_buffer(const MxLog *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_log__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxLog *mx_log__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (MxLog *)protobuf_c_message_unpack(&mx_log__descriptor, allocator, len, data);
}
void mx_log__free_unpacked(MxLog *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_log__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void mx_store_info__init(MxStoreInfo *message) {
  static const MxStoreInfo init_value = MX_STORE_INFO__INIT;
  *message = init_value;
}
size_t mx_store_info__get_packed_size(const MxStoreInfo *message) {
  assert(message->base.descriptor == &mx_store_info__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_store_info__pack(const MxStoreInfo *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_store_info__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_store_info__pack_to_buffer(const MxStoreInfo *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_store_info__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxStoreInfo *mx_store_info__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data) {
  return (MxStoreInfo *)protobuf_c_message_unpack(&mx_store_info__descriptor, allocator, len, data);
}
void mx_store_info__free_unpacked(MxStoreInfo *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_store_info__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
void mx_store_update__init(MxStoreUpdate *message) {
  static const MxStoreUpdate init_value = MX_STORE_UPDATE__INIT;
  *message = init_value;
}
size_t mx_store_update__get_packed_size(const MxStoreUpdate *message) {
  assert(message->base.descriptor == &mx_store_update__descriptor);
  return protobuf_c_message_get_packed_size((const ProtobufCMessage *)(message));
}
size_t mx_store_update__pack(const MxStoreUpdate *message, uint8_t *out) {
  assert(message->base.descriptor == &mx_store_update__descriptor);
  return protobuf_c_message_pack((const ProtobufCMessage *)message, out);
}
size_t mx_store_update__pack_to_buffer(const MxStoreUpdate *message, ProtobufCBuffer *buffer) {
  assert(message->base.descriptor == &mx_store_update__descriptor);
  return protobuf_c_message_pack_to_buffer((const ProtobufCMessage *)message, buffer);
}
MxStoreUpdate *mx_store_update__unpack(ProtobufCAllocator *allocator, size_t len,
                                       const uint8_t *data) {
  return (MxStoreUpdate *)protobuf_c_message_unpack(&mx_store_update__descriptor, allocator, len,
                                                    data);
}
void mx_store_update__free_unpacked(MxStoreUpdate *message, ProtobufCAllocator *allocator) {
  if (!message) return;
  assert(message->base.descriptor == &mx_store_update__descriptor);
  protobuf_c_message_free_unpacked((ProtobufCMessage *)message, allocator);
}
static const ProtobufCFieldDescriptor mx_log__field_descriptors[1] = {
  {
      "log", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
      offsetof(MxLog, log), NULL, NULL, 0,                       /* flags */
      0, NULL, NULL                                              /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_log__field_indices_by_name[] = {
  0, /* field[0] = log */
};
static const ProtobufCIntRange mx_log__number_ranges[1 + 1] = { { 1, 0 }, { 0, 1 } };
const ProtobufCMessageDescriptor mx_log__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxLog",
  "MxLog",
  "MxLog",
  "",
  sizeof(MxLog),
  1,
  mx_log__field_descriptors,
  mx_log__field_indices_by_name,
  1,
  mx_log__number_ranges,
  (ProtobufCMessageInit)mx_log__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor mx_store_info__field_descriptors[3] = {
  {
      "key", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64, 0, /* quantifier_offset */
      offsetof(MxStoreInfo, key), NULL, NULL, 0,                  /* flags */
      0, NULL, NULL                                               /* reserved1,reserved2, etc */
  },
  {
      "type", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_ENUM, 0,        /* quantifier_offset */
      offsetof(MxStoreInfo, type), &mx_store_type__descriptor, NULL, 0, /* flags */
      0, NULL, NULL /* reserved1,reserved2, etc */
  },
  {
      "msg", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
      offsetof(MxStoreInfo, msg), NULL, NULL, 0,                 /* flags */
      0, NULL, NULL                                              /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_store_info__field_indices_by_name[] = {
  0, /* field[0] = key */
  2, /* field[2] = msg */
  1, /* field[1] = type */
};
static const ProtobufCIntRange mx_store_info__number_ranges[1 + 1] = { { 1, 0 }, { 0, 3 } };
const ProtobufCMessageDescriptor mx_store_info__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxStoreInfo",
  "MxStoreInfo",
  "MxStoreInfo",
  "",
  sizeof(MxStoreInfo),
  3,
  mx_store_info__field_descriptors,
  mx_store_info__field_indices_by_name,
  1,
  mx_store_info__number_ranges,
  (ProtobufCMessageInit)mx_store_info__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
static const ProtobufCFieldDescriptor mx_store_update__field_descriptors[4] = {
  {
      "key", 1, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_UINT64, 0, /* quantifier_offset */
      offsetof(MxStoreUpdate, key), NULL, NULL, 0,                /* flags */
      0, NULL, NULL                                               /* reserved1,reserved2, etc */
  },
  {
      "type", 2, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_ENUM, 0,          /* quantifier_offset */
      offsetof(MxStoreUpdate, type), &mx_store_type__descriptor, NULL, 0, /* flags */
      0, NULL, NULL /* reserved1,reserved2, etc */
  },
  {
      "msg", 3, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
      offsetof(MxStoreUpdate, msg), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                              /* reserved1,reserved2, etc */
  },
  {
      "mask", 4, PROTOBUF_C_LABEL_NONE, PROTOBUF_C_TYPE_BYTES, 0, /* quantifier_offset */
      offsetof(MxStoreUpdate, mask), NULL, NULL, 0,               /* flags */
      0, NULL, NULL                                               /* reserved1,reserved2, etc */
  },
};
static const unsigned mx_store_update__field_indices_by_name[] = {
  0, /* field[0] = key */
  3, /* field[3] = mask */
  2, /* field[2] = msg */
  1, /* field[1] = type */
};
static const ProtobufCIntRange mx_store_update__number_ranges[1 + 1] = { { 1, 0 }, { 0, 4 } };
const ProtobufCMessageDescriptor mx_store_update__descriptor = {
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MxStoreUpdate",
  "MxStoreUpdate",
  "MxStoreUpdate",
  "",
  sizeof(MxStoreUpdate),
  4,
  mx_store_update__field_descriptors,
  mx_store_update__field_indices_by_name,
  1,
  mx_store_update__number_ranges,
  (ProtobufCMessageInit)mx_store_update__init,
  NULL,
  NULL,
  NULL /* reserved[123] */
};
static const ProtobufCEnumValue mx_store_type__enum_values_by_number[10] = {
  { "LOG", "MX_STORE_TYPE__LOG", 0 },           { "GPIO", "MX_STORE_TYPE__GPIO", 1 },
  { "ADS1015", "MX_STORE_TYPE__ADS1015", 2 },   { "MCP2515", "MX_STORE_TYPE__MCP2515", 3 },
  { "ADS1259", "MX_STORE_TYPE__ADS1259", 4 },   { "ADT7476A", "MX_STORE_TYPE__ADT7476A", 5 },
  { "ADC", "MX_STORE_TYPE__ADC", 6 },           { "PCA9539R", "MX_STORE_TYPE__PCA9539R", 7 },
  { "MCP23008", "MX_STORE_TYPE__MCP23008", 8 }, { "END", "MX_STORE_TYPE__END", 9 },
};
static const ProtobufCIntRange mx_store_type__value_ranges[] = { { 0, 0 }, { 0, 10 } };
static const ProtobufCEnumValueIndex mx_store_type__enum_values_by_name[10] = {
  { "ADC", 6 },  { "ADS1015", 2 }, { "ADS1259", 4 },  { "ADT7476A", 5 }, { "END", 9 },
  { "GPIO", 1 }, { "LOG", 0 },     { "MCP23008", 8 }, { "MCP2515", 3 },  { "PCA9539R", 7 },
};
const ProtobufCEnumDescriptor mx_store_type__descriptor = {
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "MxStoreType",
  "MxStoreType",
  "MxStoreType",
  "",
  10,
  mx_store_type__enum_values_by_number,
  10,
  mx_store_type__enum_values_by_name,
  1,
  mx_store_type__value_ranges,
  NULL,
  NULL,
  NULL,
  NULL /* reserved[1234] */
};
