#pragma once

typedef enum {
  FRONT_POWER_DISTRIBUTION_CAN_EVENT_RX = 0,
  FRONT_POWER_DISTRIBUTION_CAN_EVENT_TX,
  FRONT_POWER_DISTRIBUTION_CAN_EVENT_FAULT,
  NUM_FRONT_POWER_DISTRIBUTION_CAN_EVENTS,
} FrontPowerDistributionCanEvent;

typedef enum {
  FRONT_POWER_DISTRIBUTION_GPIO_EVENT_DRIVER_DISPLAY = NUM_FRONT_POWER_DISTRIBUTION_CAN_EVENTS + 1,
  FRONT_POWER_DISTRIBUTION_GPIO_EVENT_STEERING,
  FRONT_POWER_DISTRIBUTION_GPIO_EVENT_CENTRE_CONSOLE,
  FRONT_POWER_DISTRIBUTION_GPIO_EVENT_HEADLIGHTS,
  FRONT_POWER_DISTRIBUTION_GPIO_EVENT_SIGNAL_LEFT,
  FRONT_POWER_DISTRIBUTION_GPIO_EVENT_SIGNAL_RIGHT,
  FRONT_POWER_DISTRIBUTION_GPIO_EVENT_SIGNAL_HAZARD,
  NUM_FRONT_POWER_DISTRIBUTION_GPIO_EVENTS,
} FrontPowerDistributionGpioEvent;

typedef enum {
  FRONT_POWER_DISTRIBUTION_SIGNAL_EVENT_LEFT = NUM_FRONT_POWER_DISTRIBUTION_GPIO_EVENTS + 1,
  FRONT_POWER_DISTRIBUTION_SIGNAL_EVENT_RIGHT,
  FRONT_POWER_DISTRIBUTION_SIGNAL_EVENT_HAZARD,
  NUM_FRONT_POWER_DISTRIBUTION_SIGNAL_EVENTS,
} FrontPowerDistributionSignalEvent;

typedef enum {
  FRONT_POWER_DISTRIBUTION_CURRENT_SENSE_EVENT_DATA_READY =
      NUM_FRONT_POWER_DISTRIBUTION_SIGNAL_EVENTS + 1,
  NUM_FRONT_POWER_DISTRIBUTION_CURRENT_SENSE_EVENTS,
} FrontPowerDistributionCurrentSenseEvent;
