package canmsgdefs

// NOTE: This file is generated by codegen-tooling.
// Currently, this file is copy-pasted from codegen output
// to canmsgdefs in the telemetry server.

// TODO: Automate this process.

// CanDeviceID is a 16-bit integer for the source of a CAN message
type CanDeviceId uint16

// CanMsgID is a 32-bit integer for the type of CAN message
type CanMsgId uint32

// For setting the CAN device
const (
	SystemCanDeviceReserved               CanDeviceID = 0
	SystemCanDeviceBmsCarrier             CanDeviceID = 1
	SystemCanDeviceCentreConsole          CanDeviceID = 2
	SystemCanDevicePowerDistributionRear  CanDeviceID = 3
	SystemCanDevicePowerDistributionFront CanDeviceID = 4
	SystemCanDeviceMotorController        CanDeviceID = 5
	SystemCanDevicePedal                  CanDeviceID = 6
	SystemCanDeviceSteering               CanDeviceID = 7
	SystemCanDeviceSolar                  CanDeviceID = 8
	SystemCanDeviceCharger                CanDeviceID = 10
	SystemCanDeviceImu                    CanDeviceID = 11
	SystemCanDevicePowerSelection         CanDeviceID = 12
	SystemCanDeviceBabydriver             CanDeviceID = 15
)

// For setting the CAN message ID
const (
	SystemCanMessageBpsHeartbeat              CanMsgID = 0
	SystemCanMessageSetRelayStates            CanMsgID = 1
	SystemCanMessagePowertrainHeartbeat       CanMsgID = 3
	SystemCanMessageGetAuxStatus              CanMsgID = 4
	SystemCanMessageFaultSequence             CanMsgID = 5
	SystemCanMessagePowerOnMainSequence       CanMsgID = 6
	SystemCanMessagePowerOffSequence          CanMsgID = 7
	SystemCanMessagePowerOnAuxSequence        CanMsgID = 8
	SystemCanMessageDriveOutput               CanMsgID = 9
	SystemCanMessageSetEbrakeState            CanMsgID = 10
	SystemCanMessageOvuvDcdcAux               CanMsgID = 16
	SystemCanMessageMcErrorLimits             CanMsgID = 17
	SystemCanMessagePedalOutput               CanMsgID = 18
	SystemCanMessageCruiseTarget              CanMsgID = 19
	SystemCanMessageBrake                     CanMsgID = 20
	SystemCanMessageFrontPower                CanMsgID = 21
	SystemCanMessageDriveState                CanMsgID = 22
	SystemCanMessageLightsSync                CanMsgID = 23
	SystemCanMessageLights                    CanMsgID = 24
	SystemCanMessageHorn                      CanMsgID = 25
	SystemCanMessageGetChargerConnectionState CanMsgID = 26
	SystemCanMessageSetChargerRelay           CanMsgID = 27
	SystemCanMessageBeginPrecharge            CanMsgID = 28
	SystemCanMessagePrechargeCompleted        CanMsgID = 29
	SystemCanMessageHazard                    CanMsgID = 30
	SystemCanMessageDischargePrecharge        CanMsgID = 31
	SystemCanMessageBatteryVt                 CanMsgID = 32
	SystemCanMessageBatteryAggregateVc        CanMsgID = 33
	SystemCanMessageStateTransitionFault      CanMsgID = 34
	SystemCanMessageMotorControllerVc         CanMsgID = 35
	SystemCanMessageMotorVelocity             CanMsgID = 36
	SystemCanMessageMotorDebug                CanMsgID = 37
	SystemCanMessageMotorTemps                CanMsgID = 38
	SystemCanMessageMotorAmpHr                CanMsgID = 39
	SystemCanMessageOdometer                  CanMsgID = 40
	SystemCanMessageCruiseControlCommand      CanMsgID = 41
	SystemCanMessageAuxDcdcVc                 CanMsgID = 43
	SystemCanMessageDcdcTemps                 CanMsgID = 44
	SystemCanMessageUvCutoffNotification      CanMsgID = 45
	SystemCanMessageChargerInfo               CanMsgID = 47
	SystemCanMessageRequestToCharge           CanMsgID = 48
	SystemCanMessageAllowCharging             CanMsgID = 49
	SystemCanMessageChargerConnectedState     CanMsgID = 50
	SystemCanMessageLinearAcceleration        CanMsgID = 51
	SystemCanMessageAngularRotation           CanMsgID = 52
	SystemCanMessageChargerFault              CanMsgID = 53
	SystemCanMessageFrontCurrentMeasurement   CanMsgID = 54
	SystemCanMessageRearCurrentMeasurement    CanMsgID = 55
	SystemCanMessageAuxBatteryStatus          CanMsgID = 56
	SystemCanMessageBatteryFanState           CanMsgID = 57
	SystemCanMessageBatteryRelayState         CanMsgID = 58
	SystemCanMessageSolarData                 CanMsgID = 59
	SystemCanMessageSolarFault                CanMsgID = 60
	SystemCanMessageRearPdFault               CanMsgID = 61
	SystemCanMessageFrontPdFault              CanMsgID = 62
	SystemCanMessageBabydriver                CanMsgID = 63
)
