/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: adc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "adc.pb-c.h"
void   mu_adc_store__init
                     (MuAdcStore         *message)
{
  static const MuAdcStore init_value = MU_ADC_STORE__INIT;
  *message = init_value;
}
size_t mu_adc_store__get_packed_size
                     (const MuAdcStore *message)
{
  assert(message->base.descriptor == &mu_adc_store__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mu_adc_store__pack
                     (const MuAdcStore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mu_adc_store__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mu_adc_store__pack_to_buffer
                     (const MuAdcStore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mu_adc_store__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MuAdcStore *
       mu_adc_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MuAdcStore *)
     protobuf_c_message_unpack (&mu_adc_store__descriptor,
                                allocator, len, data);
}
void   mu_adc_store__free_unpacked
                     (MuAdcStore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mu_adc_store__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mu_adc_store__field_descriptors[1] =
{
  {
    "reading",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MuAdcStore, n_reading),
    offsetof(MuAdcStore, reading),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mu_adc_store__field_indices_by_name[] = {
  0,   /* field[0] = reading */
};
static const ProtobufCIntRange mu_adc_store__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mu_adc_store__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MuAdcStore",
  "MuAdcStore",
  "MuAdcStore",
  "",
  sizeof(MuAdcStore),
  1,
  mu_adc_store__field_descriptors,
  mu_adc_store__field_indices_by_name,
  1,  mu_adc_store__number_ranges,
  (ProtobufCMessageInit) mu_adc_store__init,
  NULL,NULL,NULL    /* reserved[123] */
};
