/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ads1259.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ads1259.pb-c.h"
void   mu_ads1259_store__init
                     (MuAds1259Store         *message)
{
  static const MuAds1259Store init_value = MU_ADS1259_STORE__INIT;
  *message = init_value;
}
size_t mu_ads1259_store__get_packed_size
                     (const MuAds1259Store *message)
{
  assert(message->base.descriptor == &mu_ads1259_store__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mu_ads1259_store__pack
                     (const MuAds1259Store *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mu_ads1259_store__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mu_ads1259_store__pack_to_buffer
                     (const MuAds1259Store *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mu_ads1259_store__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MuAds1259Store *
       mu_ads1259_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MuAds1259Store *)
     protobuf_c_message_unpack (&mu_ads1259_store__descriptor,
                                allocator, len, data);
}
void   mu_ads1259_store__free_unpacked
                     (MuAds1259Store *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mu_ads1259_store__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mu_ads1259_store__field_descriptors[1] =
{
  {
    "reading",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(MuAds1259Store, reading),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mu_ads1259_store__field_indices_by_name[] = {
  0,   /* field[0] = reading */
};
static const ProtobufCIntRange mu_ads1259_store__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mu_ads1259_store__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MuAds1259Store",
  "MuAds1259Store",
  "MuAds1259Store",
  "",
  sizeof(MuAds1259Store),
  1,
  mu_ads1259_store__field_descriptors,
  mu_ads1259_store__field_indices_by_name,
  1,  mu_ads1259_store__number_ranges,
  (ProtobufCMessageInit) mu_ads1259_store__init,
  NULL,NULL,NULL    /* reserved[123] */
};
