/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: adt7476a.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "adt7476a.pb-c.h"
void   mu_adt7476a_store__init
                     (MuAdt7476aStore         *message)
{
  static const MuAdt7476aStore init_value = MU_ADT7476A_STORE__INIT;
  *message = init_value;
}
size_t mu_adt7476a_store__get_packed_size
                     (const MuAdt7476aStore *message)
{
  assert(message->base.descriptor == &mu_adt7476a_store__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mu_adt7476a_store__pack
                     (const MuAdt7476aStore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mu_adt7476a_store__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mu_adt7476a_store__pack_to_buffer
                     (const MuAdt7476aStore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mu_adt7476a_store__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MuAdt7476aStore *
       mu_adt7476a_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MuAdt7476aStore *)
     protobuf_c_message_unpack (&mu_adt7476a_store__descriptor,
                                allocator, len, data);
}
void   mu_adt7476a_store__free_unpacked
                     (MuAdt7476aStore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mu_adt7476a_store__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mu_adt7476a_store__field_descriptors[2] =
{
  {
    "speed",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(MuAdt7476aStore, n_speed),
    offsetof(MuAdt7476aStore, speed),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(MuAdt7476aStore, n_status),
    offsetof(MuAdt7476aStore, status),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mu_adt7476a_store__field_indices_by_name[] = {
  0,   /* field[0] = speed */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange mu_adt7476a_store__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor mu_adt7476a_store__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MuAdt7476aStore",
  "MuAdt7476aStore",
  "MuAdt7476aStore",
  "",
  sizeof(MuAdt7476aStore),
  2,
  mu_adt7476a_store__field_descriptors,
  mu_adt7476a_store__field_indices_by_name,
  1,  mu_adt7476a_store__number_ranges,
  (ProtobufCMessageInit) mu_adt7476a_store__init,
  NULL,NULL,NULL    /* reserved[123] */
};
