/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gpio.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gpio.pb-c.h"
void   mu_gpio_store__init
                     (MuGpioStore         *message)
{
  static const MuGpioStore init_value = MU_GPIO_STORE__INIT;
  *message = init_value;
}
size_t mu_gpio_store__get_packed_size
                     (const MuGpioStore *message)
{
  assert(message->base.descriptor == &mu_gpio_store__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mu_gpio_store__pack
                     (const MuGpioStore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mu_gpio_store__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mu_gpio_store__pack_to_buffer
                     (const MuGpioStore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mu_gpio_store__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MuGpioStore *
       mu_gpio_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MuGpioStore *)
     protobuf_c_message_unpack (&mu_gpio_store__descriptor,
                                allocator, len, data);
}
void   mu_gpio_store__free_unpacked
                     (MuGpioStore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mu_gpio_store__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mu_gpio_store__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(MuGpioStore, n_state),
    offsetof(MuGpioStore, state),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mu_gpio_store__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange mu_gpio_store__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mu_gpio_store__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MuGpioStore",
  "MuGpioStore",
  "MuGpioStore",
  "",
  sizeof(MuGpioStore),
  1,
  mu_gpio_store__field_descriptors,
  mu_gpio_store__field_indices_by_name,
  1,  mu_gpio_store__number_ranges,
  (ProtobufCMessageInit) mu_gpio_store__init,
  NULL,NULL,NULL    /* reserved[123] */
};
