/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pca9539r.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "pca9539r.pb-c.h"
void   mu_pca9539r_store__init
                     (MuPca9539rStore         *message)
{
  static const MuPca9539rStore init_value = MU_PCA9539R_STORE__INIT;
  *message = init_value;
}
size_t mu_pca9539r_store__get_packed_size
                     (const MuPca9539rStore *message)
{
  assert(message->base.descriptor == &mu_pca9539r_store__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t mu_pca9539r_store__pack
                     (const MuPca9539rStore *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &mu_pca9539r_store__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t mu_pca9539r_store__pack_to_buffer
                     (const MuPca9539rStore *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &mu_pca9539r_store__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
MuPca9539rStore *
       mu_pca9539r_store__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (MuPca9539rStore *)
     protobuf_c_message_unpack (&mu_pca9539r_store__descriptor,
                                allocator, len, data);
}
void   mu_pca9539r_store__free_unpacked
                     (MuPca9539rStore *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &mu_pca9539r_store__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor mu_pca9539r_store__field_descriptors[1] =
{
  {
    "state",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(MuPca9539rStore, n_state),
    offsetof(MuPca9539rStore, state),
    NULL,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_PACKED,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned mu_pca9539r_store__field_indices_by_name[] = {
  0,   /* field[0] = state */
};
static const ProtobufCIntRange mu_pca9539r_store__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor mu_pca9539r_store__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "MuPca9539rStore",
  "MuPca9539rStore",
  "MuPca9539rStore",
  "",
  sizeof(MuPca9539rStore),
  1,
  mu_pca9539r_store__field_descriptors,
  mu_pca9539r_store__field_indices_by_name,
  1,  mu_pca9539r_store__number_ranges,
  (ProtobufCMessageInit) mu_pca9539r_store__init,
  NULL,NULL,NULL    /* reserved[123] */
};
