#pragma once

// Standard configurations for power_distribution_can_rx_event_mapper.

#include "can_rx_event_mapper.h"

extern const PowerDistributionCanRxEventMapperConfig FRONT_POWER_DISTRIBUTION_CAN_RX_CONFIG;
extern const PowerDistributionCanRxEventMapperConfig REAR_POWER_DISTRIBUTION_CAN_RX_CONFIG;
