#pragma once

// Current IDs used by current_measurement and publish_data.

// These are specified at https://uwmidsun.atlassian.net/wiki/x/AYCsRw, please change there
// if you update here.
typedef enum {
  // Currents for front power distribution
  FRONT_CURRENT_CENTRE_CONSOLE = 0,
  FRONT_CURRENT_PEDAL,
  FRONT_CURRENT_STEERING,
  FRONT_CURRENT_LEFT_CAMERA,
  FRONT_CURRENT_RIGHT_CAMERA,
  FRONT_CURRENT_DRIVER_DISPLAY,
  FRONT_CURRENT_INFOTAINMENT_DISPLAY,
  FRONT_CURRENT_REAR_DISPLAY,
  FRONT_CURRENT_LEFT_DRIVER_DISPLAY,
  FRONT_CURRENT_RIGHT_DRIVER_DISPLAY,
  FRONT_CURRENT_MAIN_PI,
  FRONT_CURRENT_LEFT_FRONT_TURN_LIGHT,
  FRONT_CURRENT_RIGHT_FRONT_TURN_LIGHT,
  FRONT_CURRENT_DAYTIME_RUNNING_LIGHTS,
  FRONT_CURRENT_SPEAKER,
  FRONT_CURRENT_HORN,
  FRONT_CURRENT_FAN_1,
  FRONT_CURRENT_FAN_2,
  FRONT_CURRENT_5V_SPARE_1,
  FRONT_CURRENT_5V_SPARE_2,
  FRONT_CURRENT_SPARE_1,
  FRONT_CURRENT_SPARE_2,
  FRONT_CURRENT_SPARE_3,

  // Currents for rear power distribution
  REAR_CURRENT_BMS,
  REAR_CURRENT_MCI,
  REAR_CURRENT_CHARGER,
  REAR_CURRENT_SOLAR_SENSE,
  REAR_CURRENT_TELEMETRY,
  REAR_CURRENT_REAR_CAMERA,
  REAR_CURRENT_LEFT_REAR_TURN_LIGHT,
  REAR_CURRENT_RIGHT_REAR_TURN_LIGHT,
  REAR_CURRENT_BRAKE_LIGHT,
  REAR_CURRENT_STROBE,
  REAR_CURRENT_FAN_1,
  REAR_CURRENT_FAN_2,
  REAR_CURRENT_SPARE_1,
  REAR_CURRENT_SPARE_2,
  REAR_CURRENT_SPARE_3,
  REAR_CURRENT_SPARE_4,
  REAR_CURRENT_SPARE_5,
  REAR_CURRENT_SPARE_6,
  REAR_CURRENT_SPARE_7,
  REAR_CURRENT_SPARE_8,
  REAR_CURRENT_SPARE_9,
  REAR_CURRENT_SPARE_10,

  NUM_CURRENTS,
} PowerDistributionCurrent;
