#pragma once

// NOT YET GENERIC

typedef enum {
  POWER_DISTRIBUTION_CAN_EVENT_RX = 0,
  POWER_DISTRIBUTION_CAN_EVENT_TX,
  POWER_DISTRIBUTION_CAN_EVENT_FAULT,
  NUM_POWER_DISTRIBUTION_CAN_EVENTS,
} PowerDistributionCanEvent;

typedef enum {
  POWER_DISTRIBUTION_GPIO_EVENT_DRIVER_DISPLAY = NUM_POWER_DISTRIBUTION_CAN_EVENTS + 1,
  POWER_DISTRIBUTION_GPIO_EVENT_STEERING,
  POWER_DISTRIBUTION_GPIO_EVENT_CENTRE_CONSOLE,
  POWER_DISTRIBUTION_GPIO_EVENT_DRL,
  POWER_DISTRIBUTION_GPIO_EVENT_PEDAL,
  POWER_DISTRIBUTION_GPIO_EVENT_HORN,
  POWER_DISTRIBUTION_GPIO_EVENT_SIGNAL_LEFT,
  POWER_DISTRIBUTION_GPIO_EVENT_SIGNAL_RIGHT,
  POWER_DISTRIBUTION_GPIO_EVENT_SIGNAL_HAZARD,
  NUM_POWER_DISTRIBUTION_GPIO_EVENTS,
} PowerDistributionGpioEvent;

typedef enum {
  POWER_DISTRIBUTION_SIGNAL_EVENT_LEFT = NUM_POWER_DISTRIBUTION_GPIO_EVENTS + 1,
  POWER_DISTRIBUTION_SIGNAL_EVENT_RIGHT,
  POWER_DISTRIBUTION_SIGNAL_EVENT_HAZARD,
  NUM_POWER_DISTRIBUTION_SIGNAL_EVENTS,
} PowerDistributionSignalEvent;

typedef enum {
  POWER_DISTRIBUTION_CURRENT_SENSE_EVENT_DATA_READY = NUM_POWER_DISTRIBUTION_SIGNAL_EVENTS + 1,
  NUM_POWER_DISTRIBUTION_CURRENT_SENSE_EVENTS,
} PowerDistributionCurrentSenseEvent;
