# Defines $(T)_SRC, $(T)_INC, $(T)_DEPS, and $(T)_CFLAGS for the build makefile.
# Tests can be excluded by defining $(T)_EXCLUDE_TESTS.
# Pre-defined:
# $(T)_SRC_ROOT: $(T)_DIR/src
# $(T)_INC_DIRS: $(T)_DIR/inc{/$(PLATFORM)}
# $(T)_SRC: $(T)_DIR/src{/$(PLATFORM)}/*.{c,s}

# The code in this library is autogenerated and can be updated using:
#   $ make generate_motor_can_c_code

$(T)_SRC_ROOT := $($(T)_DIR)

$(T)_INC_DIRS := $($(T)_DIR)
$(T)_SRC := $(wildcard $($(T)_SRC_ROOT)/*.c)
