#pragma once

// Defines events used in solar.

#include "event_queue.h"

#define DATA_READY_EVENT_PRIORITY EVENT_PRIORITY_NORMAL
#define RELAY_EVENT_PRIORITY EVENT_PRIORITY_HIGH

typedef enum {
  SOLAR_CAN_EVENT_RX = 0,
  SOLAR_CAN_EVENT_TX,
  SOLAR_CAN_EVENT_FAULT,
  NUM_SOLAR_CAN_EVENTS,
} SolarCanEvent;

typedef enum {
  SOLAR_MCP3427_EVENT_DATA_TRIGGER = NUM_SOLAR_CAN_EVENTS + 1,
  SOLAR_MCP3427_EVENT_DATA_READY,
  NUM_SOLAR_MCP3427_EVENTS
} SolarMcp3427Event;

typedef enum {
  DATA_READY_EVENT = NUM_SOLAR_MCP3427_EVENTS + 1,
  NUM_SOLAR_DATA_EVENTS,
} SolarDataEvent;

// Used by solar_fsm internally.
typedef enum {
  SOLAR_RELAY_EVENT_CLOSE = NUM_SOLAR_DATA_EVENTS + 1,
  SOLAR_RELAY_EVENT_OPEN,
  NUM_SOLAR_RELAY_EVENTS,
} SolarRelayEvent;
