#pragma once

typedef enum {
  CHARGER_CAN_EVENT_RX = 0,
  CHARGER_CAN_EVENT_TX,
  CHARGER_CAN_EVENT_FAULT,
  NUM_CHARGER_CAN_EVENTS
} ChargerCanEvent;

typedef enum {
  CHARGER_CHARGE_EVENT_BEGIN = NUM_CHARGER_CAN_EVENTS + 1,
  CHARGER_CHARGE_EVENT_STOP,
  NUM_CHARGER_CHARGE_EVENTS
} ChargerChargeEvent;
