#pragma once

#include "status.h"

#define CHARGER_CONNECTION_SENSE_POLL_RATE_MS 500

#define CHARGER_CONNECTION_SENSE_PORT GPIO_PORT_A
#define CHARGER_CONNECTION_SENSE_PIN 7

#define CHARGER_CS_UNPLUGGED_LOWER 2233
#define CHARGER_CS_UNPLUGGED_UPPER 2631
#define CHARGER_CS_PLUGGED_RELEASED_LOWER 754
#define CHARGER_CS_PLUGGED_RELEASED_UPPER 1116
#define CHARGER_CS_PLUGGED_PRESSED_LOWER 1459
#define CHARGER_CS_PLUGGED_PRESSED_UPPER 1938

typedef enum {
  CHARGER_STATE_UNPLUGGED = 0,
  CHARGER_STATE_PLUGGED_PRESSED,
  CHARGER_STATE_PLUGGED_RELEASED,
  NUM_CHARGER_CONNECTION_STATES
} ChargerConnectionState;

StatusCode connection_sense_init();
