#pragma once

typedef enum {
  CHARGER_CAN_EVENT_RX = 0,
  CHARGER_CAN_EVENT_TX,
  CHARGER_CAN_EVENT_FAULT,
  NUM_CHARGER_CAN_EVENTS
} ChargerCanEvent;

typedef enum {
  CHARGER_PWM_EVENT_REQUEST_READING = NUM_CHARGER_CAN_EVENTS + 1,
  CHARGER_PWM_EVENT_VALUE_AVAILABLE,
  NUM_PWM_EVENTS
} ChargerPwmEvent;

typedef enum {
  CHARGER_CONNECTION_EVENT_CONNECTED = NUM_PWM_EVENTS + 1,
  CHARGER_CONNECTION_EVENT_DISCONNECTED,
  NUM_CHARGER_CONNECTION_EVENTS
} ChargerConnectionEvent;

typedef enum {
  BEGIN_CHARGE_FSM_EVENT_IDLE_STATE = NUM_CHARGER_CONNECTION_EVENTS + 1,
  BEGIN_CHARGE_FSM_EVENT_PENDING_STATE,
  NUM_BEGIN_CHARGE_FSM_STATES
} ChargerFsmEvent;

typedef enum {
  CHARGER_STOP_EVENT_STOP = NUM_BEGIN_CHARGE_FSM_STATES + 1,
  NUM_CHARGER_STOP_EVENTS
} ChargerStopEvent;
