#pragma once

typedef enum {
  POWER_SELECTION_CAN_EVENT_RX = 0,
  POWER_SELECTION_CAN_EVENT_TX,
  POWER_SELECTION_CAN_EVENT_FAULT,
} PowerSelectionCanEvent;

typedef enum {
  AUX_ADC_VOLT_CHANNEL = 0,
  AUX_ADC_TEMP_CHANNEL,
  AUX_ADC_CURRENT_CHANNEL,
  NUM_AUX_ADC_CHANNELS
} AuxAdcChannel;
