
// The MIT License (MIT)

// Copyright (c) 2018-2019 Erik Moqvist

// Permission is hereby granted, free of charge, to any person
// obtaining a copy of this software and associated documentation
// files (the "Software"), to deal in the Software without
// restriction, including without limitation the rights to use, copy,
// modify, merge, publish, distribute, sublicense, and/or sell copies
// of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:

// The above copyright notice and this permission notice shall be
// included in all copies or substantial portions of the Software.

//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
// EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
// MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
// BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
// ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
// CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

// This file was generated by cantools version 32.19.0 Wed May 22 20:54:00 2019.

#include <string.h>

#include "motor_can.h"

static inline uint8_t pack_left_shift_u32(uint32_t value, uint8_t shift, uint8_t mask) {
  return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(uint32_t value, uint8_t shift, uint8_t mask) {
  return (uint8_t)((uint8_t)(value >> shift) & mask);
}

int motor_can_drive_command_pack(uint8_t *dst_p, const MotorCanDriveCommand *src_p, size_t size) {
  uint32_t motor_current;
  uint32_t motor_velocity;

  if (size < 8u) {
    return (-EINVAL);
  }

  memset(&dst_p[0], 0, 8);

  memcpy(&motor_velocity, &src_p->motor_velocity, sizeof(motor_velocity));
  dst_p[0] |= pack_left_shift_u32(motor_velocity, 0u, 0xffu);
  dst_p[1] |= pack_right_shift_u32(motor_velocity, 8u, 0xffu);
  dst_p[2] |= pack_right_shift_u32(motor_velocity, 16u, 0xffu);
  dst_p[3] |= pack_right_shift_u32(motor_velocity, 24u, 0xffu);
  memcpy(&motor_current, &src_p->motor_current, sizeof(motor_current));
  dst_p[4] |= pack_left_shift_u32(motor_current, 0u, 0xffu);
  dst_p[5] |= pack_right_shift_u32(motor_current, 8u, 0xffu);
  dst_p[6] |= pack_right_shift_u32(motor_current, 16u, 0xffu);
  dst_p[7] |= pack_right_shift_u32(motor_current, 24u, 0xffu);

  return (8);
}
