/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: adc.proto */

#ifndef PROTOBUF_C_adc_2eproto__INCLUDED
#define PROTOBUF_C_adc_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _MxAdcStore MxAdcStore;

/* --- enums --- */

/* --- messages --- */

struct _MxAdcStore {
  ProtobufCMessage base;
  size_t n_reading;
  uint32_t *reading;
};
#define MX_ADC_STORE__INIT                             \
  {                                                    \
    PROTOBUF_C_MESSAGE_INIT(&mx_adc_store__descriptor) \
    , 0, NULL                                          \
  }

/* MxAdcStore methods */
void mx_adc_store__init(MxAdcStore *message);
size_t mx_adc_store__get_packed_size(const MxAdcStore *message);
size_t mx_adc_store__pack(const MxAdcStore *message, uint8_t *out);
size_t mx_adc_store__pack_to_buffer(const MxAdcStore *message, ProtobufCBuffer *buffer);
MxAdcStore *mx_adc_store__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void mx_adc_store__free_unpacked(MxAdcStore *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MxAdcStore_Closure)(const MxAdcStore *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mx_adc_store__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_adc_2eproto__INCLUDED */
