/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ads1259.proto */

#ifndef PROTOBUF_C_ads1259_2eproto__INCLUDED
#define PROTOBUF_C_ads1259_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _MxAds1259Store MxAds1259Store;

/* --- enums --- */

/* --- messages --- */

struct _MxAds1259Store {
  ProtobufCMessage base;
  uint32_t reading;
};
#define MX_ADS1259_STORE__INIT                             \
  {                                                        \
    PROTOBUF_C_MESSAGE_INIT(&mx_ads1259_store__descriptor) \
    , 0                                                    \
  }

/* MxAds1259Store methods */
void mx_ads1259_store__init(MxAds1259Store *message);
size_t mx_ads1259_store__get_packed_size(const MxAds1259Store *message);
size_t mx_ads1259_store__pack(const MxAds1259Store *message, uint8_t *out);
size_t mx_ads1259_store__pack_to_buffer(const MxAds1259Store *message, ProtobufCBuffer *buffer);
MxAds1259Store *mx_ads1259_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                         const uint8_t *data);
void mx_ads1259_store__free_unpacked(MxAds1259Store *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MxAds1259Store_Closure)(const MxAds1259Store *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mx_ads1259_store__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_ads1259_2eproto__INCLUDED */
