/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: adt7476a.proto */

#ifndef PROTOBUF_C_adt7476a_2eproto__INCLUDED
#define PROTOBUF_C_adt7476a_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _MxAdt7476aStore MxAdt7476aStore;

/* --- enums --- */

/* --- messages --- */

struct _MxAdt7476aStore {
  ProtobufCMessage base;
  size_t n_speed;
  uint32_t *speed;
  size_t n_status;
  protobuf_c_boolean *status;
};
#define MX_ADT7476A_STORE__INIT                             \
  {                                                         \
    PROTOBUF_C_MESSAGE_INIT(&mx_adt7476a_store__descriptor) \
    , 0, NULL, 0, NULL                                      \
  }

/* MxAdt7476aStore methods */
void mx_adt7476a_store__init(MxAdt7476aStore *message);
size_t mx_adt7476a_store__get_packed_size(const MxAdt7476aStore *message);
size_t mx_adt7476a_store__pack(const MxAdt7476aStore *message, uint8_t *out);
size_t mx_adt7476a_store__pack_to_buffer(const MxAdt7476aStore *message, ProtobufCBuffer *buffer);
MxAdt7476aStore *mx_adt7476a_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                           const uint8_t *data);
void mx_adt7476a_store__free_unpacked(MxAdt7476aStore *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MxAdt7476aStore_Closure)(const MxAdt7476aStore *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mx_adt7476a_store__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_adt7476a_2eproto__INCLUDED */
