/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: mcp23008.proto */

#ifndef PROTOBUF_C_mcp23008_2eproto__INCLUDED
#define PROTOBUF_C_mcp23008_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _MxMcp23008Store MxMcp23008Store;

/* --- enums --- */

/* --- messages --- */

struct _MxMcp23008Store {
  ProtobufCMessage base;
  size_t n_state;
  protobuf_c_boolean *state;
};
#define MX_MCP23008_STORE__INIT                             \
  {                                                         \
    PROTOBUF_C_MESSAGE_INIT(&mx_mcp23008_store__descriptor) \
    , 0, NULL                                               \
  }

/* MxMcp23008Store methods */
void mx_mcp23008_store__init(MxMcp23008Store *message);
size_t mx_mcp23008_store__get_packed_size(const MxMcp23008Store *message);
size_t mx_mcp23008_store__pack(const MxMcp23008Store *message, uint8_t *out);
size_t mx_mcp23008_store__pack_to_buffer(const MxMcp23008Store *message, ProtobufCBuffer *buffer);
MxMcp23008Store *mx_mcp23008_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                           const uint8_t *data);
void mx_mcp23008_store__free_unpacked(MxMcp23008Store *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MxMcp23008Store_Closure)(const MxMcp23008Store *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mx_mcp23008_store__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_mcp23008_2eproto__INCLUDED */
