/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: pca9539r.proto */

#ifndef PROTOBUF_C_pca9539r_2eproto__INCLUDED
#define PROTOBUF_C_pca9539r_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _MxPca9539rStore MxPca9539rStore;

/* --- enums --- */

/* --- messages --- */

struct _MxPca9539rStore {
  ProtobufCMessage base;
  size_t n_state;
  protobuf_c_boolean *state;
};
#define MX_PCA9539R_STORE__INIT                             \
  {                                                         \
    PROTOBUF_C_MESSAGE_INIT(&mx_pca9539r_store__descriptor) \
    , 0, NULL                                               \
  }

/* MxPca9539rStore methods */
void mx_pca9539r_store__init(MxPca9539rStore *message);
size_t mx_pca9539r_store__get_packed_size(const MxPca9539rStore *message);
size_t mx_pca9539r_store__pack(const MxPca9539rStore *message, uint8_t *out);
size_t mx_pca9539r_store__pack_to_buffer(const MxPca9539rStore *message, ProtobufCBuffer *buffer);
MxPca9539rStore *mx_pca9539r_store__unpack(ProtobufCAllocator *allocator, size_t len,
                                           const uint8_t *data);
void mx_pca9539r_store__free_unpacked(MxPca9539rStore *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MxPca9539rStore_Closure)(const MxPca9539rStore *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCMessageDescriptor mx_pca9539r_store__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_pca9539r_2eproto__INCLUDED */
