/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: stores.proto */

#ifndef PROTOBUF_C_stores_2eproto__INCLUDED
#define PROTOBUF_C_stores_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003003 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

typedef struct _MxLog MxLog;
typedef struct _MxStoreInfo MxStoreInfo;
typedef struct _MxStoreUpdate MxStoreUpdate;

/* --- enums --- */

typedef enum _MxStoreType {
  MX_STORE_TYPE__LOG = 0,
  MX_STORE_TYPE__GPIO = 1,
  MX_STORE_TYPE__ADS1015 = 2,
  MX_STORE_TYPE__MCP2515 = 3,
  MX_STORE_TYPE__ADS1259 = 4,
  MX_STORE_TYPE__ADT7476A = 5,
  MX_STORE_TYPE__ADC = 6,
  MX_STORE_TYPE__PCA9539R = 7,
  MX_STORE_TYPE__MCP23008 = 8,
  MX_STORE_TYPE__END = 9 PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(MX_STORE_TYPE)
} MxStoreType;

/* --- messages --- */

struct _MxLog {
  ProtobufCMessage base;
  ProtobufCBinaryData log;
};
#define MX_LOG__INIT                             \
  {                                              \
    PROTOBUF_C_MESSAGE_INIT(&mx_log__descriptor) \
    , {                                          \
      0, NULL                                    \
    }                                            \
  }

struct _MxStoreInfo {
  ProtobufCMessage base;
  uint64_t key;
  MxStoreType type;
  ProtobufCBinaryData msg;
};
#define MX_STORE_INFO__INIT                             \
  {                                                     \
    PROTOBUF_C_MESSAGE_INIT(&mx_store_info__descriptor) \
    , 0, MX_STORE_TYPE__LOG, {                          \
      0, NULL                                           \
    }                                                   \
  }

struct _MxStoreUpdate {
  ProtobufCMessage base;
  uint64_t key;
  MxStoreType type;
  ProtobufCBinaryData msg;
  ProtobufCBinaryData mask;
};
#define MX_STORE_UPDATE__INIT                             \
  {                                                       \
    PROTOBUF_C_MESSAGE_INIT(&mx_store_update__descriptor) \
    , 0, MX_STORE_TYPE__LOG, { 0, NULL }, {               \
      0, NULL                                             \
    }                                                     \
  }

/* MxLog methods */
void mx_log__init(MxLog *message);
size_t mx_log__get_packed_size(const MxLog *message);
size_t mx_log__pack(const MxLog *message, uint8_t *out);
size_t mx_log__pack_to_buffer(const MxLog *message, ProtobufCBuffer *buffer);
MxLog *mx_log__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void mx_log__free_unpacked(MxLog *message, ProtobufCAllocator *allocator);
/* MxStoreInfo methods */
void mx_store_info__init(MxStoreInfo *message);
size_t mx_store_info__get_packed_size(const MxStoreInfo *message);
size_t mx_store_info__pack(const MxStoreInfo *message, uint8_t *out);
size_t mx_store_info__pack_to_buffer(const MxStoreInfo *message, ProtobufCBuffer *buffer);
MxStoreInfo *mx_store_info__unpack(ProtobufCAllocator *allocator, size_t len, const uint8_t *data);
void mx_store_info__free_unpacked(MxStoreInfo *message, ProtobufCAllocator *allocator);
/* MxStoreUpdate methods */
void mx_store_update__init(MxStoreUpdate *message);
size_t mx_store_update__get_packed_size(const MxStoreUpdate *message);
size_t mx_store_update__pack(const MxStoreUpdate *message, uint8_t *out);
size_t mx_store_update__pack_to_buffer(const MxStoreUpdate *message, ProtobufCBuffer *buffer);
MxStoreUpdate *mx_store_update__unpack(ProtobufCAllocator *allocator, size_t len,
                                       const uint8_t *data);
void mx_store_update__free_unpacked(MxStoreUpdate *message, ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*MxLog_Closure)(const MxLog *message, void *closure_data);
typedef void (*MxStoreInfo_Closure)(const MxStoreInfo *message, void *closure_data);
typedef void (*MxStoreUpdate_Closure)(const MxStoreUpdate *message, void *closure_data);

/* --- services --- */

/* --- descriptors --- */

extern const ProtobufCEnumDescriptor mx_store_type__descriptor;
extern const ProtobufCMessageDescriptor mx_log__descriptor;
extern const ProtobufCMessageDescriptor mx_store_info__descriptor;
extern const ProtobufCMessageDescriptor mx_store_update__descriptor;

PROTOBUF_C__END_DECLS

#endif /* PROTOBUF_C_stores_2eproto__INCLUDED */
