/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_UPDATE_NAME_PB_H_INCLUDED
#define PB_UPDATE_NAME_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _UpdateName { 
    pb_callback_t new_name; 
} UpdateName;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define UpdateName_init_default                  {{{NULL}, NULL}}
#define UpdateName_init_zero                     {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define UpdateName_new_name_tag                  1

/* Struct field encoding specification for nanopb */
#define UpdateName_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   new_name,          1)
#define UpdateName_CALLBACK pb_default_field_callback
#define UpdateName_DEFAULT NULL

extern const pb_msgdesc_t UpdateName_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UpdateName_fields &UpdateName_msg

/* Maximum encoded size of messages (where known) */
/* UpdateName_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
