/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6-dev */

#ifndef PB_UPDATE_ID_PB_H_INCLUDED
#define PB_UPDATE_ID_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _UpdateId {
  uint32_t new_id;
} UpdateId;

#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define UpdateId_init_default \
  { 0 }
#define UpdateId_init_zero \
  { 0 }

/* Field tags (for use in manual encoding/decoding) */
#define UpdateId_new_id_tag 1

/* Struct field encoding specification for nanopb */
#define UpdateId_FIELDLIST(X, a) X(a, STATIC, SINGULAR, UINT32, new_id, 1)
#define UpdateId_CALLBACK NULL
#define UpdateId_DEFAULT NULL

extern const pb_msgdesc_t UpdateId_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UpdateId_fields &UpdateId_msg

/* Maximum encoded size of messages (where known) */
#define UpdateId_size 6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
