#pragma once

typedef enum {
  SMOKE_LTC_AFE_TRIGGER_CELL_CONV_EVENT = 0,
  SMOKE_LTC_AFE_CELL_CONV_COMPLETE_EVENT,
  SMOKE_LTC_AFE_TRIGGER_AUX_CONV_EVENT,
  SMOKE_LTC_AFE_AUX_CONV_COMPLETE_EVENT,
  SMOKE_LTC_AFE_CALLBACK_RUN_EVENT,
  SMOKE_LTC_AFE_FAULT_EVENT,
  NUM_SMOKE_LTC_EVENTS,
} SmokeLtcAfeEvents;
