#!/usr/bin/env bash
echo "Automatically formatting and linting" && make format_quick && git add . && make lint_quick

if [ $? -ne 0 ]; then
 echo "Code must be properly formatted before commiting!"
 exit 1
fi

if [[ $GIT_AUTHOR_NAME == 'vagrant' || $GIT_AUTHOR_EMAIL == 'vagrant@midsunbox' ]]; then
  echo "You didn't set up your git config! Please follow the Software 101 modules on Confluence."
  echo "https://uwmidsun.atlassian.net/wiki/spaces/ELEC/pages/60260353/Module+1+Setup"
  exit 1
fi