#pragma once

// Standard hardware configurations for rear_power_distribution_current_measurement.

#include "rear_power_distribution_current_measurement.h"

#define REAR_POWER_DISTRIBUTION_DSEL_I2C_ADDRESS 0x20

typedef enum {
  REAR_POWER_DISTRIBUTION_CURRENT_CTR_BRK_LIGHT = 0,
  REAR_POWER_DISTRIBUTION_CURRENT_STROBE,
  REAR_POWER_DISTRIBUTION_CURRENT_LEFT_BRK_LIGHT,
  REAR_POWER_DISTRIBUTION_CURRENT_RIGHT_BRK_LIGHT,
  REAR_POWER_DISTRIBUTION_CURRENT_LEFT_TURN,
  REAR_POWER_DISTRIBUTION_CURRENT_RIGHT_TURN,
  REAR_POWER_DISTRIBUTION_CURRENT_SOLAR,
  REAR_POWER_DISTRIBUTION_CURRENT_TELEMETRY,
  NUM_REAR_POWER_DISTRIBUTION_CURRENTS,
} RearPowerDistributionCurrent;

typedef enum {
  // first thing named is when DSEL is 0, then when DSEL is 1
  REAR_POWER_DISTRIBUTION_BTS7200_CTR_BRK_STROBE = 0,
  REAR_POWER_DISTRIBUTION_BTS7200_LEFT_RIGHT_BRK_LIGHT,
  REAR_POWER_DISTRIBUTION_BTS7200_LEFT_RIGHT_TURN,
  REAR_POWER_DISTRIBUTION_BTS7200_SOLAR_TELEMETRY,
  // there's also a CAM_CHARGER bts7200 on the rear board (?)
  NUM_REAR_POWER_DISTRIBUTION_BTS7200_CHANNELS,
} RearPowerDistributionBts7200;

extern const RearPowerDistributionCurrentHardwareConfig REAR_POWER_DISTRIBUTION_HW_CONFIG;
