#pragma once
// Provides an autogenerated version string to uniquely identify commits and
// the status of the working tree. This takes the form of the following string:
//
//   7ad414f8-dirty
//     ^       ^
//     |       |
//     |       +-- dirty status flag
//     +---------- git hash
//
// One can simply checkout the branch via the commit hash:
//
//    $ git checkout 7ad414f8
//
// Or search for the branch that contains this commit:
//
//    $ git branch --contains 7ad414f8

// Dump the version string over UART via the logging functions. This should be
// called during initialization.
void git_version_init(void);
