#pragma once

//Events IDs for digital input
typedef enum {
  STEERING_DIGITAL_INPUT_EVENT_HORN = 0,
  STEERING_DIGITAL_INPUT_EVENT_RADIO_PPT,
  STEERING_DIGITAL_INPUT_EVENT_HIGH_BEAM_FWD,
  STEERING_DIGITAL_INPUT_EVENT_HIGH_BEAM_BACK,
  STEERING_DIGITAL_INPUT_EVENT_REGEN_BRAKE_TOGGLE,
  STEERING_DIGITAL_INPUT_EVENT_HEADLIGHTS_ON_OFF,
  STEERING_DIGITAL_INPUT_EVENT_CC_ON_OFF,
  STEERING_DIGITAL_DIGITAL_INPUT_EVENT_CC_INCREASE_SPEED,
  STEERING_DIGITAL_DIGITAL_INPUT_EVENT_Cc_DECREASE_SPEED,
  NUM_STEERING_DIGITAL_INPUT_EVENTS,
} SteeringInterfaceEvents;