#pragma once 

//Digital Inputs
#define STEERING_CONFIG_PIN_HORN \
  { GPIO_PORT_B, 1 }
#define STEERING_CONFIG_PIN_RADIO_PPT \
  { GPIO_PORT_B, 0 }
#define STEERING_CONFIG_PIN_HIGH_BEAM_FWD \
  { GPIO_PORT_A, 7 }
#define STEERING_CONFIG_PIN_HIGH_BEAM_BACK \
  { GPIO_PORT_A, 8 }
#define STEERING_CONFIG_HEADLIGHTS_ON_OFF \
  { GPIO_PORT_A, 6 }
#define STEERING_CONFIG_PIN_REGEN_BREAK_TOGGLE \
  { GPIO_PORT_A, 9 }
#define STEERING_CONFIG_PIN_CC_ON_OFF \
  { GPIO_PORT_A, 5 }
#define STEERING_CONFIG_PIN_CC_INCREASE_SPEED \
  { GPIO_PORT_A, 4 }
#define STEERING_CONFIG_PIN_CC_DECREASE_SPEED \
  { GPIO_PORT_A, 3 }

//CAN
#define STEERING_CONFIG_PIN_CAN_TX \
  { GPIO_PORT_A, 12 }
#define STEERING_CONFIG_PIN_CAN_RX \
  { GPIO_PORT_A, 11 }

  