#pragma once

// Events IDs for digital input
typedef enum {
  STEERING_DIGITAL_INPUT_EVENT_HORN = 0,
  // push to talk radio
  STEERING_DIGITAL_INPUT_EVENT_RADIO_PPT,
  STEERING_DIGITAL_INPUT_EVENT_HIGH_BEAM_FORWARD,
  STEERING_DIGITAL_INPUT_EVENT_HIGH_BEAM_REAR,
  STEERING_DIGITAL_INPUT_EVENT_REGEN_BRAKE_TOGGLE,
  STEERING_DIGITAL_INPUT_EVENT_CC_TOGGLE,
  STEERING_DIGITAL_DIGITAL_INPUT_EVENT_CC_INCREASE_SPEED,
  STEERING_DIGITAL_DIGITAL_INPUT_EVENT_CC_DECREASE_SPEED,
  STEERING_DIGITAL_INPUT_EVENT_CAN_TX,
  STEERING_DIGITAL_INPUT_EVENT_CAN_RX,
  NUM_STEERING_DIGITAL_INPUT_EVENTS,

} SteeringInterfaceEvents;