#pragma once

typedef enum {
  BMS_CAN_EVENT_RX = 0,
  BMS_CAN_EVENT_TX,
  BMS_CAN_EVENT_FAULT,
  INVALID_BMS_CAN_EVENT
} BmsCanEvent;
#define NUM_BMS_CAN_EVENTS (INVALID_BMS_CAN_EVENT - BMS_CAN_EVENT_RX + 1)

typedef enum {
  BMS_AFE_EVENT_TRIGGER_CELL_CONV = INVALID_BMS_CAN_EVENT + 1,
  BMS_AFE_EVENT_CELL_CONV_COMPLETE,
  BMS_AFE_EVENT_TRIGGER_AUX_CONV,
  BMS_AFE_EVENT_AUX_CONV_COMPLETE,
  BMS_AFE_EVENT_CALLBACK_RUN,
  BMS_AFE_EVENT_FAULT,
  INVALID_BMS_AFE_EVENT
} BmsAfeEvent;
#define NUM_BMS_AFE_EVENTS (INVALID_BMS_AFE_EVENT - BMS_AFE_EVENT_TRIGGER_CELL_CONV + 1)
