#pragma once

typedef enum {
  BMS_CAN_EVENT_RX = 0,
  BMS_CAN_EVENT_TX,
  BMS_CAN_EVENT_FAULT,
  BMS_CAN_EVENT_END
} BmsCanEvent;

typedef enum {
  BMS_AFE_EVENT_TRIGGER_CELL_CONV = BMS_CAN_EVENT_END + 1,
  BMS_AFE_EVENT_CELL_CONV_COMPLETE,
  BMS_AFE_EVENT_TRIGGER_AUX_CONV,
  BMS_AFE_EVENT_AUX_CONV_COMPLETE,
  BMS_AFE_EVENT_CALLBACK_RUN,
  BMS_AFE_EVENT_FAULT,
  BMS_AFE_EVENT_END
} BmsAfeEvent;
