typedef enum {
  CENTRE_CONSOLE_POWER_EVENT_OFF = 0,
  CENTRE_CONSOLE_POWER_EVENT_ON,
  CENTRE_CONSOLE_POWER_EVENT_FAULT,
  CENTRE_CONSOLE_POWER_EVENT_PUBLISH_FAULT,
  CENTRE_CONSOLE_POWER_EVENT_FAULTS_CLEARED,
  CENTRE_CONSOLE_POWER_EVENT_CLEAR_FAULT,
  NUM_CENTRE_CONSOLE_POWER_EVENTS
} CentreConsolePowerEvent;

typedef enum {
  POWER_ON_SEQUENCE_EVENT_BEGIN = NUM_CENTRE_CONSOLE_POWER_EVENTS,
  POWER_ON_SEQUENCE_EVENT_COMPLETE, 
  NUM_POWER_ON_SEQUENCE_EVENTS
} PowerOnSequenceEvent;

typedef enum {
  POWER_OFF_SEQUENCE_EVENT_BEGIN = NUM_POWER_ON_SEQUENCE_EVENTS,
  POWER_OFF_SEQUENCE_EVENT_COMPLETE,
  NUM_POWER_OFF_SEQUENCE_EVENTS
} PowerOffSequenceEvent;

typedef enum {
  CENTRE_CONSOLE_BUTTON_PRESS_EVENT_DRIVE = 12,
  CENTRE_CONSOLE_BUTTON_PRESS_EVENT_REVERSE,
  CENTRE_CONSOLE_BUTTON_PRESS_EVENT_POWER,
  CENTRE_CONSOLE_BUTTON_PRESS_EVENT_NEUTRAL,
  CENTRE_CONSOLE_BUTTON_PRESS_EVENT_HAZARD,
  CENTRE_CONSOLE_BUTTON_PRESS_EVENT_EMERGENCY_STOP
} CentreConsoleButtonPressEvent;
